version: "3"

services:
  website:
    build: .
    env_file:
      - docker.env
    entrypoint: ["./boot.sh"]
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - .:/home/objdetect/objectdetect
    depends_on:
      - cloud-sql-proxy
      - redis

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: ["./cloud_sql_proxy",
              "-instances=gluegun-app:us-central1:gc-instance=tcp:0.0.0.0:5432",
              "-credential_file=/secrets/cloudsql/credentials.json"]
    volumes:
      - ./credentials.json:/secrets/cloudsql/credentials.json
    ports:
      - 5432

  rq_worker:
    build: worker/.
    depends_on:
      - redis

  redis:
    image: redis:alpine