version: "3"

services:
  website:
    build: .
    env_file:
      - docker.env
    ports:
      - 5000:5000
    volumes:
      - .:/home/objdetect/objectdetect
    depends_on:
      - cloud-sql-proxy

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: ["./cloud_sql_proxy",
              "-instances=gluegun-app:us-central1:gc-instance=tcp:0.0.0.0:5432",
              "-credential_file=/secrets/cloudsql/credentials.json"]
    volumes:
      - ./credentials.json:/secrets/cloudsql/credentials.json
    ports:
      - 5432
#TODO how to map volume without replacing venv? Maybe add code to a subfolder instead of home path like /app/objdetect